### ISSUE TITLE
Netzwerk-Kommunikation einrichten 

### ISSUE THREAD

**Issue by AlexWirthAAU** [AlexWirthAAU/DieSiedlerVonCatan#3]
Um das Spiel gemeinsam spielen zu können müssen sich mindestens 3 Spieler im lokalen Netzwerk finden und vernetzen können

**Comment by ChrissiSenger** [comment]
- [x] Als Spieler möchte ich einen Spielernamen angeben

- [x] Als Spieler möchte ich in der Spielerliste aufscheinen

- [x] Als Spieler möchte ich meine Mitspieler auswählen, um mit ihnen ein Spiel zu starten

**Comment by ChrissiSenger** [comment]
- [x] Als Spieler möchte ich eine Farbe wählen

**Comment by ChrissiSenger** [comment]
- [x] Als Spieler möchte ich wieder ins Spiel zurückkehren können

- [x] Als Spieler möchte ich von der Spielerliste verschwinden, wenn ich die App schließe.

- [x] Als Spieler möchte ich von der Spielerliste verschwinden, wenn ich zurückgehe.

- [x] Als Spieler möchte ich von der Spielerliste verschwinden, wenn ein Spiel mit mir gestartet wird.
