### ISSUE TITLE
Spieler anlegen

### ISSUE THREAD

**Issue by AlexWirthAAU** [AlexWirthAAU/DieSiedlerVonCatan#38]
Der Spieler soll mindestens einen Namen und eine Spielfarbe haben.

**Comment by ChrissiSenger** [comment]
Da ich um die Mitspieler auszuwählen und das Spiel zu starten (siehe #3) dem User bereits Namen und Farbe zuordne, geht das  unter einem. Von der Komplexität der Implementierung zum ins Spiel zurückkehren (zB. bei Verbindungsverlust seitens des Clients) hängt es ab, ob User=Spieler oder eine Überklasse von Spieler ist.
