### ISSUE TITLE
Spielzüge pro Runde erzeugen 

### ISSUE THREAD

**Issue by AlexWirthAAU** [AlexWirthAAU/DieSiedlerVonCatan#4]
Pro Runde soll der Spieler einen der folgenden Aktionen ausführen können:
Würfeln +
Bauen (Dorf, Straße, Stadt) oder
Handeln oder
Entwicklungskarte kaufen oder 
Räuber verstellen wenn Würfelzahl 7

**Comment by ChrissiSenger** [comment]
Entwicklungskarte ausspielen soll auch möglich sein
