### ISSUE TITLE
Baupunkt auswählen

### ISSUE THREAD

**Issue by klemensvo** [AlexWirthAAU/DieSiedlerVonCatan#40]
Der Spieler, der an der Reihe ist, kann einen Spielpunkt (road, settlement, city) auswählen (um später darauf zu bauen). - Das Spiel meldet zurück, ob hier gebaut werden kann (z.B. "Straße hier errichten?") oder dass hier nicht gebaut werden kann (z.B. "hier kann keine Siedlung errichtet werden!")

Die Bedienung erfolgt ja normalerweise mit dem Finger, nicht mit dem Cursor auf dem Emulator, dadurch wir die oben gemeinte Abfrage notwendig, so zielsicher trifft man wahrscheinlich den gewünschten Punkt nicht...

Alex hat gemeint, dass das schon in der GameboardClickListener-Klasse ist, dort muss man dann nur einen kleinen Alert (oder so was) einfügen, ist so gesehen wahrscheinlich kein eigener Punkt

**Comment by klemensvo** [comment]
Die Bedienung erfolgt ja normalerweise mit dem Finger, nicht mit dem Cursor auf dem Emulator, dadurch wir die oben gemeinte Abfrage notwendig, so zielsicher trifft man wahrscheinlich den gewünschten Punkt nicht... 
Alex hat gemeint, dass das schon in der GameboardClickListener-Klasse ist, dort muss man dann nur einen kleinen Alert (oder so was) einfügen, ist so gesehen wahrscheinlich kein eigener Punkt

**Comment by ChrissiSenger** [comment]
#29
